# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    pre_install:
      - uv sync --group doc
    build:
      html:
        - uv run mkdocs build --strict -d $READTHEDOCS_OUTPUT/html
